# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
  - task: NuGetToolInstaller@1
  
  - bash: |
      chmod +x fake_build.sh
      ./fake_build.sh

  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: 'App center connection'
      appSlug: 'TheCodingSanta/FakeNukeTryout'
      appFile: '/artifacts/com.codingsanta.fakenuketryout-Signed.apk'
      symbolsOption: 'Android'
      releaseNotesOption: 'input'
      releaseNotesInput: 'First attempt to connect'
      destinationType: 'groups'